name: Continuous Integration with Github Actions - Pagamentos

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0.29
        env:
          MYSQL_ROOT_PASSWORD: admin123
          MYSQL_DATABASE: pagamentos
        ports:
          - 3308:3308
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3.3.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Wait for MySQL to be ready
      run: |
        for i in `seq 1 30`; do
        nc -z localhost 3306 && echo Success && exit 0 || echo "Waiting for MySQL..."
        sleep 2
        done
        echo "MySQL did not become ready in time" && exit 1
        
    - name: Build with Maven
      working-directory: ./continuous-integration-pagamentos/ms-pagamento
      run: mvn clean package
      env:
        SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3308/pagamentos?createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=UTC&useSSL=false
        SPRING_DATASOURCE_USERNAME: root
        SPRING_DATASOURCE_PASSWORD: admin123

#    - name: Run tests
#      working-directory: ./continuous-integration-pagamentos/ms-pagamento
#      run: mvn test

    - name: Docker Compose Build
      working-directory: ./continuous-integration-pagamentos
      run: docker compose build

    - name: Push to Docker Hub Container Registry
      run: |
        docker tag ${{ secrets.DOCKER_USERNAME }}/ms-pagamento:latest ${{ secrets.DOCKER_USERNAME }}/ms-pagamento:${{ github.run_id }}

        docker push ${{ secrets.DOCKER_USERNAME }}/ms-pagamento::${{ github.run_id }}
        docker push ${{ secrets.DOCKER_USERNAME }}/ms-pagamento:latest


    # # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    # - name: Update dependency graph
    #   uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
